CREATE TABLE RESIDENTES(
    DNI_RESIDENTE               VARCHAR2(9),
    NOMBRE                      VARCHAR2(100),
    APELLIDOS                   VARCHAR2(100),
    TELEFONO_CONTACTO           VARCHAR2(13),
    FECHA_NACIMIENTO            DATE,
    ACTIVO                      NUMBER(1)DEFAULT 1,
    CONSTRAINT PK_RESIDENTES PRIMARY KEY (DNI_RESIDENTE),
    CONSTRAINT NN_RESIDENTES_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_APELLIDOS CHECK (APELLIDOS IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_TELEFONO_CONTA CHECK (TELEFONO_CONTACTO IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_ACTIVO CHECK (ACTIVO IS NOT NULL)
);
CREATE TABLE ESTANCIA(
    HABITACION                  NUMBER(2),
    FECHA_ENTRADA               DATE,
    FECHA_SALIDA                DATE,
    DNI_RESIDENTE               VARCHAR2(9),               
    COSTE_MENSUAL               NUMBER(8,2),
    CONSTRAINT PK_ESTANCIA PRIMARY KEY (HABITACION),
    CONSTRAINT NN_ESTANCIA_COSTE_MENSUAL CHECK (COSTE_MENSUAL IS NOT NULL),
    CONSTRAINT CK_ESTANCIA_COSTE_MENSUAL_POS CHECK (COSTE_MENSUAL >0)
);
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO                  NUMBER(3),
    NOMBRE                          VARCHAR(100),    
    CONSTRAINT PK_ID_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL)
    );
CREATE TABLE TRATAMIENTO(
    ID_TRATAMIENTO                  NUMBER(3),
    ID_MEDICAMENTO                  NUMBER(3),
    FECHA_FIN                       DATE,
    FECHA_INICIO                    DATE,
    CANT_DESAYUNO                   NUMBER,
    CANT_COMIDA                     NUMBER,
    CANT_CENA                       NUMBER,    
    CONSTRAINT PK_ID_TRATAMIENTO PRIMARY KEY (ID_TRATAMIENTO)
);

CREATE TABLE TOMAS(
    ID_TRATAMIENTO                  NUMBER(3),
    DNI_RESIDENTE                   VARCHAR2(9),    
    CONSTRAINT PK_ID_TRATAMIENTO_DNI_RESIDENTE PRIMARY KEY (ID_TRATAMIENTO, DNI_RESIDENTE)
);

CREATE TABLE COMIDAS_SEMANA (
    DNI_RESIDENTE           VARCHAR2(9),
    ID_MENU_LUNES           NUMBER(3),
    ID_MENU_MARTES          NUMBER(3),
    ID_MENU_MIERCOLES       NUMBER(3),
    ID_MENU_JUEVES          NUMBER(3),
    ID_MENU_VIERNES         NUMBER(3),
    ID_MENU_SABADO          NUMBER(3),
    ID_MENU_DOMINGO         NUMBER(3),    
    CONSTRAINT PK_COMIDAS_SEMANA PRIMARY KEY (ID_MENU_LUNES, ID_MENU_MARTES, ID_MENU_MIERCOLES, ID_MENU_JUEVES, ID_MENU_VIERNES, ID_MENU_SABADO, ID_MENU_DOMINGO)
);

CREATE TABLE COMIDAS (
    ID_COMIDA               NUMBER(3),
    NOMBRE                  VARCHAR2(100),    
    CONSTRAINT PK_ID_COMIDA PRIMARY KEY (ID_COMIDA) 
);

CREATE TABLE MENU (
    ID_MENU                 NUMBER(3),
    NOMBRE                  VARCHAR2(100),
    ID_DESAYUNO             NUMBER(3),
    ID_ALMUERZO             NUMBER(3),
    ID_CENA                 NUMBER(3),   
    CONSTRAINT PK_ID_MENU PRIMARY KEY (ID_MENU)
);

--restricciones

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_COMIDAS_SEMANA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE)ON DELETE CASCADE;

ALTER TABLE ESTANCIA
ADD CONSTRAINT FK_CESTANCIA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE) ON DELETE SET NULL;

ALTER TABLE TRATAMIENTO
ADD CONSTRAINT FK_TRATAMIENTO_MEDICAMENTO_ FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_TRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE);

ALTER TABLE MENU
ADD CONSTRAINT FK_DESAYUNO FOREIGN KEY (ID_DESAYUNO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_ALMUERZO FOREIGN KEY (ID_ALMUERZO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_CENA FOREIGN KEY (ID_CENA) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_LUNES FOREIGN KEY (ID_MENU_LUNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MARTES FOREIGN KEY (ID_MENU_MARTES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MIERCOLES FOREIGN KEY (ID_MENU_MIERCOLES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_JUEVES FOREIGN KEY (ID_MENU_JUEVES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_VIERNES FOREIGN KEY (ID_MENU_VIERNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_SABADO FOREIGN KEY (ID_MENU_SABADO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_DOMINGO FOREIGN KEY (ID_MENU_DOMINGO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

--secuencias

CREATE SEQUENCE ID_MEDICAMENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ID_TRATAMIENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SECUENCIA_HABITACION
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMIDAS --Antonio
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_MENU
START WITH 1
INCREMENT BY 1;


--datos fernando




--DATOS santi

--MEDICAMENTO
--
INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'SIMVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'ASPIRINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'OMEOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LEXOTIROXINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'RAMIPRIL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PARACETAMOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'VENTOLIN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FLIXOTIDE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORTASEC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'SILDENAFILO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALMAX');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ATORVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LANSOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PULMICOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PRIMPERAN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMOXICILINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'TRAMADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARCOXIA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'BRUFEN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'METROTREXATO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'RISPERDAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ROPINIROL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LIPITOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LISONOPRIL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CINFAMRED');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALOPURINOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALPRAZOLAM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMISULPRIDA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMOROLFINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ANASTROZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'APULCO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARACENAC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARANESP');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARIPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZITROMICINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AXAVAST');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AVONEX');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AVONEXTUN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZYDROP');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZZALURE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FODONAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FOLIFERRON');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FOMED');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORMODUAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORMULAEXPEC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'SOSADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CARRACADIUM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JALDONIUM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'GONZATEM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CIRSTAMIDOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FRENADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FUROSEMIDA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'UZUMADIOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LUCITUN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYREMADEL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYREMADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYCOMPA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JENTADUETO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVITY');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVITYDOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVTANA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEXT');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JURNISTA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JUSTEGAS');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALIPERIDONA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALLADONE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALONOSFTRON');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALONTRON');

--

--TRATAMIENTO
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 11, '08/12/2020', '28/02/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 16, '10/03/2020', '22/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 38, '18/12/2020', '20/01/2021', 1.5, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '21/02/2020', '28/01/2021', 2, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 53, '23/08/2020', '23/01/2021', 1.5, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 64, '14/06/2020', '07/02/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 37, '14/06/2020', '08/01/2021', 1, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 27, '07/10/2020', '05/01/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 51, '17/09/2020', '22/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 39, '29/03/2020', '30/01/2021', 1.5, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '12/03/2020', '05/02/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 52, '21/08/2020', '20/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 1, '03/06/2020', '07/01/2021', 1, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 23, '27/07/2020', '05/01/2021', 2, 2.0, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 35, '13/06/2020', '31/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 70, '25/06/2020', '30/01/2021', 1, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 63, '30/01/2020', '27/02/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 42, '08/10/2020', '06/01/2021', 2, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '26/01/2020', '13/02/2021', 2, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 63, '10/04/2020', '13/02/2021', 2.0, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 34, '02/02/2020', '29/01/2021', 2.0, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 43, '20/06/2020', '09/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 1, '09/07/2020', '12/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '26/08/2020', '16/01/2021', 2, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 26, '09/06/2020', '11/02/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 65, '20/04/2020', '17/02/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 10, '24/08/2020', '07/02/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 64, '24/08/2020', '17/01/2021', 1, 2, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 58, '05/09/2020', '25/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 63, '16/10/2020', '30/01/2021', 1, 1.5, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 46, '11/06/2020', '06/02/2021', 1.5, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 34, '13/10/2020', '06/01/2021', 1, 2.0, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 26, '30/05/2020', '17/02/2021', 2, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 35, '10/09/2020', '24/02/2021', 2, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 66, '28/12/2020', '13/01/2021', 2, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 50, '01/10/2020', '11/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '06/03/2020', '26/01/2021', 2, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 14, '26/10/2020', '27/01/2021', 1, 1, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '17/03/2020', '08/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 16, '21/12/2020', '11/02/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '29/01/2020', '16/02/2021', 2, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 44, '26/04/2020', '15/02/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 34, '25/05/2020', '03/01/2021', 1.5, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 3, '09/07/2020', '13/02/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '02/01/2020', '01/02/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 38, '06/10/2020', '22/02/2021', 2, 2.0, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 12, '25/10/2020', '13/02/2021', 1, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 27, '03/03/2020', '07/02/2021', 2, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 32, '20/06/2020', '19/02/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '29/11/2020', '13/02/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '16/10/2020', '07/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 66, '07/12/2020', '04/02/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 66, '05/06/2020', '08/02/2021', 1.5, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 64, '19/01/2020', '11/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 9, '24/10/2020', '28/01/2021', 2.0, 2.0, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 2, '13/02/2020', '10/02/2021', 1.5, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '13/12/2020', '12/02/2021', 1.5, 2.0, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 31, '08/05/2020', '08/01/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 56, '23/11/2020', '25/02/2021', 2, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '04/10/2020', '08/01/2021', 1.5, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 2, '09/06/2020', '27/01/2021', 2, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 30, '02/04/2020', '18/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 66, '28/09/2020', '14/02/2021', 2, 2, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '01/01/2020', '10/02/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 30, '17/01/2020', '03/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '19/01/2020', '11/01/2021', 2, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 67, '04/06/2020', '27/02/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 65, '02/08/2020', '19/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 49, '25/06/2020', '26/01/2021', 1.5, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '02/11/2020', '13/01/2021', 1, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '04/02/2020', '06/02/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 49, '11/03/2020', '08/01/2021', 1.5, 1.5, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 59, '07/05/2020', '06/01/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '28/08/2020', '18/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 29, '26/05/2020', '17/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 11, '29/07/2020', '22/02/2021', 1, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 64, '21/04/2020', '14/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 16, '29/04/2020', '22/02/2021', 1, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 65, '08/10/2020', '05/02/2021', 1, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 13, '27/12/2020', '02/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 35, '16/05/2020', '04/02/2021', 1.5, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 7, '05/01/2020', '09/01/2021', 1.5, 2.0, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 56, '29/08/2020', '14/02/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 55, '24/08/2020', '15/02/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 14, '29/03/2020', '18/01/2021', 1.5, 2.0, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 25, '21/09/2020', '15/01/2021', 2, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 1, '20/10/2020', '27/01/2021', 1.5, 1.5, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 14, '02/07/2020', '20/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 15, '26/09/2020', '04/01/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 21, '13/06/2020', '11/01/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 38, '04/10/2020', '14/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 61, '19/06/2020', '03/02/2021', 1, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 37, '22/10/2020', '08/01/2021', 2, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 5, '24/08/2020', '05/02/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 65, '22/11/2020', '07/02/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 44, '14/01/2020', '10/01/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 4, '27/07/2020', '23/02/2021', 2, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 24, '05/02/2020', '18/02/2021', 1, 2.0, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 11, '05/06/2020', '27/02/2021', 1.5, 1.5, 1);

--


--Tomas
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '14614884V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (67, '44260529L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (20, '04520380Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (15, '36525356E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (21, '82892604Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (4, '90582763T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (59, '72159016N');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (2, '61154110P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '44711723E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '88540285Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (7, '77846787K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '63977915B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (41, '03824738E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (49, '70262260C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (11, '28914518E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (10, '14531311A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (42, '52928178A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '42847690R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (30, '68773353H');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '39966518Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (4, '10824052E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (36, '38161249V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (17, '38253813Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (69, '50355534R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (40, '32642747C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (34, '92675304R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (40, '91852906Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (31, '05926530M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (14, '61680166P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (69, '14244665Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (48, '64977208T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (14, '74107944N');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '53926270X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '04819525J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (65, '49876260R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (60, '64086883M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (45, '87796056L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '74653744E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (11, '38075022V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '48243010G');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '00939919R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (59, '91611991R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (44, '64531364B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (19, '74620501Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (16, '11671324C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (49, '19347929F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (24, '56496188T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (27, '90282676V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (18, '23337521L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (8, '34012909A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (52, '80977688R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (6, '02300227C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (11, '76725023J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (41, '53608983P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (35, '89240904F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (70, '37847688S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (47, '25869114W');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (52, '39071272E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (11, '20088838V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '57073266P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (3, '54921800P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '16106215M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (24, '17518926X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (6, '76411132A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (18, '24142774L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (20, '09878555D');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (67, '90321486A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (19, '67134116Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (60, '31613152C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (41, '80831406E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (35, '91284240T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (58, '04198734S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '03931812P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '99240073H');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (61, '21889814R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '53813264A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (64, '83939464K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (57, '98541763B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (36, '74740683K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (61, '04663633S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '66425557Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (46, '03049705C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (6, '10418714J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (36, '67360665J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (24, '43808467E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (19, '34351579K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (40, '28084137X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (36, '89426223S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (45, '62939399Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '62508629B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (70, '29841379Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '59014633Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '61465745Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '83113173M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (30, '97746914L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (59, '99569728Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '47599659D');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '69328654F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (7, '99306888H');

--aCABA sANTI

--Marï¿½a

/*INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ceviche de pescado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Paella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Huevos fritos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pizza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tallarines');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa de verduras');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Empanada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pulpo a la gallega');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Calamares');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Salmorejo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lomo saltado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lentejas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Garbanzos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Croquetas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tortilla de patatas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Risotto de calabaza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Crepes de nutella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hot dogs');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cordero Liban?s');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chuletas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tostadas mexicanas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bacalao');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa mongolesa');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hamburguesas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Arroz de mariscos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fajitas de pollo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas fritas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chilli con carne');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Costillas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chipiron plancha');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cochinillo segoviano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lasaña');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Milanesa de pollo a la parmesana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas bravas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pollo asado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Albondigas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cus-cus marroqui');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Nachos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ensalada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Espinacas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Mango');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fresas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Platano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Kiwi');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Manzana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Naranjas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Uvas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones con nata');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones con nata y queso');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ardoria');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones con nata y queso');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bocata del Manolo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bocata del polvillo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bocata filete con mojo picón de Salesianos Triana cobrado por Marta');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'ColaCado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tostada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Leche');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Galletas María');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bizcocho');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Zumo de Naranja');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Zumo de Piña');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Nesquik');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cereales');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Magdalenas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Choco Flakes');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Palmeras de chocolate');*/


/*Antonio

insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 29, 40);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 1, 23);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 30, 1);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 34, 46);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 55, 51);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 21, 41);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 5, 44);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 11, 53);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 24, 50);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 41, 8);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 4, 9);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 3, 32);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 46, 24);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 55, 10);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 17, 27);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 10, 33);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 15, 31);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 62, 43, 4);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 56, 41, 1);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 6, 45);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 35, 46);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 3, 26);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 55, 54);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 15, 36);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 13, 43);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 48, 45);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 25, 6);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 42, 32);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 5, 41);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 32, 6);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 56, 35, 41);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 50, 21);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 62, 38, 53);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 55, 45);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 49, 6);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 62, 43, 34);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 24, 26);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 27, 29);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 14, 15);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 28, 39);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 52, 17);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 38, 11);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 8, 13);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 6, 54);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 23, 29);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 35, 12);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 34, 5);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 31, 21);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 36, 19);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 51, 28);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 28, 29);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 11, 42);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 48, 25);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 35, 45);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 25, 53);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 51, 55);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 23, 45);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 42, 2);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 45, 55);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 55, 6);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 56, 25, 30);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 12, 27);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 66, 20, 27);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 24, 40);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 31, 19);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 35, 12);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 17, 55);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 8, 13);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 24, 4);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 15, 29);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 47, 19);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 19, 30);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 53, 52);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 59, 9, 36);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 64, 28, 35);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 29, 19);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 4, 40);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 48, 50);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 30, 8);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 12, 6);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 34, 53);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 2, 29);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 26, 18);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 8, 24);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 62, 19, 14);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 56, 4, 51);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 55, 10);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 6, 17);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 58, 38, 39);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 67, 50, 32);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 22, 28);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 60, 53, 24);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 62, 55, 25);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 65, 45, 49);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 57, 37, 42);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 61, 6, 39);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 7, 35);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 56, 1, 30);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 55, 29, 25);
insert into MOCK_DATA (ID_MENU, NOMBRE, ID_DESAYUNO, ID_ALMUERZO, ID_CENA) values ('SEQ_MENU.NEXTVAL', '''NORMAL''', 63, 37, 14);
*/






/*
DROP TABLE RESIDENTES;
DROP TABLE ESTANCIA;
DROP TABLE MEDICAMENTO;
DROP TABLE TOMAS;
DROP TABLE TRATAMIENTO;
DROP TABLE COMIDAS_SEMANA;
DROP TABLE MENU;
DROP TABLE COMIDAS;

DROP SEQUENCE ID_MEDICAMENTO;
DROP SEQUENCE ID_TRATAMIENTO;
DROP SEQUENCE SECUENCIA_HABITACION;
DROP SEQUENCE SEQ_COMIDAS;
*/























