CREATE TABLE RESIDENTES(
    DNI_RESIDENTE               VARCHAR2(9),
    NOMBRE                      VARCHAR2(100),
    APELLIDOS                   VARCHAR2(100),
    TELEFONO_CONTACTO           VARCHAR2(13),
    FECHA_NACIMIENTO            DATE,
    ACTIVO                      NUMBER(1)DEFAULT 1,
    CONSTRAINT PK_RESIDENTES PRIMARY KEY (DNI_RESIDENTE),
    CONSTRAINT NN_RESIDENTES_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_APELLIDOS CHECK (APELLIDOS IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_TELEFONO_CONTA CHECK (TELEFONO_CONTACTO IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_ACTIVO CHECK (ACTIVO IS NOT NULL)
);
CREATE TABLE ESTANCIA(
    HABITACION                  NUMBER(2),
    FECHA_ENTRADA               DATE,
    FECHA_SALIDA                DATE,
    DNI_RESIDENTE               VARCHAR2(9),               
    COSTE_MENSUAL               NUMBER(8,2),
    CONSTRAINT PK_ESTANCIA PRIMARY KEY (HABITACION),
    CONSTRAINT NN_ESTANCIA_COSTE_MENSUAL CHECK (COSTE_MENSUAL IS NOT NULL),
    CONSTRAINT CK_ESTANCIA_COSTE_MENSUAL_POS CHECK (COSTE_MENSUAL >0)
);
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO                  NUMBER(3),
    NOMBRE                          VARCHAR(100),    
    CONSTRAINT PK_ID_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL)
    );
CREATE TABLE TRATAMIENTO(
    ID_TRATAMIENTO                  NUMBER(3),
    ID_MEDICAMENTO                  NUMBER(3),
    FECHA_FIN                       DATE,
    FECHA_INICIO                    DATE,
    CANT_DESAYUNO                   NUMBER,
    CANT_COMIDA                     NUMBER,
    CANT_CENA                       NUMBER,    
    CONSTRAINT PK_ID_TRATAMIENTO PRIMARY KEY (ID_TRATAMIENTO)
);

CREATE TABLE TOMAS(
    ID_TRATAMIENTO                  NUMBER(3),
    DNI_RESIDENTE                   VARCHAR2(9),    
    CONSTRAINT PK_ID_TRATAMIENTO_DNI_RESIDENTE PRIMARY KEY (ID_TRATAMIENTO, DNI_RESIDENTE)
);


--Antonio

CREATE TABLE COMIDAS_SEMANA (
    DNI_RESIDENTE           VARCHAR2(9),
    ID_MENU_LUNES           NUMBER(3),
    ID_MENU_MARTES          NUMBER(3),
    ID_MENU_MIERCOLES       NUMBER(3),
    ID_MENU_JUEVES          NUMBER(3),
    ID_MENU_VIERNES         NUMBER(3),
    ID_MENU_SABADO          NUMBER(3),
    ID_MENU_DOMINGO         NUMBER(3),    
    CONSTRAINT PK_COMIDAS_SEMANA PRIMARY KEY (ID_MENU_LUNES, ID_MENU_MARTES, ID_MENU_MIERCOLES, ID_MENU_JUEVES, ID_MENU_VIERNES, ID_MENU_SABADO, ID_MENU_DOMINGO)
);

CREATE TABLE COMIDAS (
    ID_COMIDA               NUMBER(3),
    NOMBRE                  VARCHAR2(100),    
    CONSTRAINT PK_ID_COMIDA PRIMARY KEY (ID_COMIDA) 
);

CREATE TABLE MENU (
    ID_MENU                 NUMBER(3),
    NOMBRE                  VARCHAR2(100),
    ID_DESAYUNO             NUMBER(3),
    ID_ALMUERZO             NUMBER(3),
    ID_CENA                 NUMBER(3),   
    CONSTRAINT PK_ID_MENU PRIMARY KEY (ID_MENU)
);

--Acaba Antonio

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_COMIDAS_SEMANA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE)ON DELETE CASCADE;

ALTER TABLE ESTANCIA
ADD CONSTRAINT FK_CESTANCIA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE) ON DELETE SET NULL;

ALTER TABLE TRATAMIENTO
ADD CONSTRAINT FK_TRATAMIENTO_MEDICAMENTO_ FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_TRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE);

--Antonio

ALTER TABLE MENU
ADD CONSTRAINT FK_DESAYUNO FOREIGN KEY (ID_DESAYUNO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_ALMUERZO FOREIGN KEY (ID_ALMUERZO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_CENA FOREIGN KEY (ID_CENA) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_LUNES FOREIGN KEY (ID_MENU_LUNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MARTES FOREIGN KEY (ID_MENU_MARTES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MIERCOLES FOREIGN KEY (ID_MENU_MIERCOLES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_JUEVES FOREIGN KEY (ID_MENU_JUEVES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_VIERNES FOREIGN KEY (ID_MENU_VIERNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_SABADO FOREIGN KEY (ID_MENU_SABADO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_DOMINGO FOREIGN KEY (ID_MENU_DOMINGO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

--Acaba Antonio


CREATE SEQUENCE ID_MEDICAMENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ID_TRATAMIENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SECUENCIA_HABITACION
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMIDAS --Antonio
START WITH 1
INCREMENT BY 1;


--datos fernando

--DATOS santi

--MEDICAMENTO
--
INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'SIMVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'ASPIRINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'OMEOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LEXOTIROXINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'RAMIPRIL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PARACETAMOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'VENTOLIN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FLIXOTIDE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORTASEC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'SILDENAFILO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALMAX');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ATORVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LANSOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PULMICOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PRIMPERAN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMOXICILINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'TRAMADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARCOXIA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'BRUFEN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'METROTREXATO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'RISPERDAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ROPINIROL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LIPITOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LISONOPRIL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CINFAMRED');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALOPURINOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALPRAZOLAM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMISULPRIDA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AMOROLFINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ANASTROZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'APULCO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARACENAC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARANESP');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ARIPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZITROMICINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AXAVAST');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AVONEX');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AVONEXTUN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZYDROP');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZZALURE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'AZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FODONAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FOLIFERRON');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FOMED');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORMODUAL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORMULAEXPEC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'SOSADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CARRACADIUM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JALDONIUM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'GONZATEM');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'CIRSTAMIDOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FRENADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FUROSEMIDA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'UZUMADIOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LUCITUN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYREMADEL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYREMADOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FYCOMPA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JENTADUETO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVITY');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVITYDOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEVTANA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JEXT');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JURNISTA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'JUSTEGAS');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALIPERIDONA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALLADONE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALONOSFTRON');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PALONTRON');

--

--TRATAMIENTO
--
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 46, '09/25/2020', '01/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 48, '01/03/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 55, '12/15/2020', '01/01/2021', 1.5, 2, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 31, '02/03/2020', '01/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 70, '11/03/2020', '01/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 50, '03/25/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 2, '12/26/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 33, '04/04/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 28, '07/11/2020', '01/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 27, '09/27/2020', '01/01/2021', 1, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 22, '04/13/2020', '01/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 30, '07/08/2020', '01/01/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 53, '08/20/2020', '01/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 44, '06/26/2020', '01/01/2021', 1, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 38, '01/31/2020', '01/01/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '11/25/2020', '01/01/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '08/12/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 70, '12/22/2020', '01/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 9, '08/18/2020', '01/01/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 43, '10/23/2020', '01/01/2021', 1, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 25, '12/11/2020', '01/01/2021', 1, 2.0, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 12, '07/03/2020', '01/01/2021', 1.5, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 38, '07/14/2020', '01/01/2021', 2, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 60, '05/03/2020', '01/01/2021', 1.5, 2, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 15, '10/18/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 63, '04/11/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 25, '01/03/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 23, '03/05/2020', '01/01/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 28, '05/11/2020', '01/01/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 36, '12/11/2020', '01/01/2021', 2.0, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 6, '03/18/2020', '01/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '07/28/2020', '01/01/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 37, '12/12/2020', '01/01/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 64, '02/25/2020', '01/01/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 4, '12/24/2020', '01/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 9, '03/19/2020', '01/01/2021', 1.5, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 32, '07/30/2020', '01/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 40, '06/21/2020', '01/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 63, '12/26/2020', '01/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 37, '12/31/2020', '01/01/2021', 1, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 55, '08/19/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 32, '11/06/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 54, '08/07/2020', '01/01/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 36, '12/22/2020', '01/01/2021', 2, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 34, '03/04/2020', '01/01/2021', 2, 1, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 39, '03/04/2020', '01/01/2021', 1.5, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 70, '05/15/2020', '01/01/2021', 2.0, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 44, '01/24/2020', '01/01/2021', 1, 2, 2.0);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 35, '02/09/2020', '01/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 44, '12/22/2020', '01/01/2021', 1, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 17, '08/17/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 4, '12/08/2020', '01/01/2021', 1, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 55, '04/15/2020', '01/01/2021', 2, 1, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 27, '01/18/2020', '01/01/2021', 1, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 45, '05/16/2020', '01/01/2021', 2, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 24, '04/26/2020', '01/01/2021', 1.5, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 70, '08/30/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 40, '04/26/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 25, '01/12/2020', '01/01/2021', 1.5, 1.5, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '12/06/2020', '01/01/2021', 2, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 20, '08/05/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 50, '09/10/2020', '01/01/2021', 1, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 41, '06/21/2020', '01/01/2021', 1.5, 1.5, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 68, '03/17/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 8, '03/14/2020', '01/01/2021', 1, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 65, '09/29/2020', '01/01/2021', 1.5, 1, 1.5);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 68, '10/04/2020', '01/01/2021', 1.5, 2, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 34, '08/13/2020', '01/01/2021', 1.5, 2, 2);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 39, '03/06/2020', '01/01/2021', 2, 1.5, 1);
insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) values (ID_TRATAMIENTO.NEXTVAL, 68, '05/25/2020', '01/01/2021', 1, 1.5, 2);

--


--Tomas
--
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (65, '14614884V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (12, '44260529L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '04520380Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (3, '36525356E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (52, '82892604Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (43, '90582763T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (63, '72159016N');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (53, '61154110P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (27, '44711723E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (2, '88540285Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (57, '77846787K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (19, '63977915B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (46, '03824738E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (5, '70262260C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (65, '28914518E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (43, '14531311A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (15, '52928178A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '42847690R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '68773353H');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (30, '39966518Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '10824052E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (4, '38161249V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (2, '38253813Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (14, '50355534R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (52, '32642747C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '92675304R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (27, '91852906Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (64, '05926530M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (57, '61680166P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (58, '14244665Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (3, '64977208T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (18, '74107944N');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (40, '53926270X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (26, '04819525J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (49, '49876260R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (42, '64086883M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (29, '87796056L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (45, '74653744E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (3, '38075022V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '48243010G');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (58, '00939919R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (64, '91611991R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (59, '64531364B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (50, '74620501Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (22, '11671324C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '19347929F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '56496188T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (24, '90282676V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (50, '23337521L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (21, '34012909A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (18, '80977688R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (14, '02300227C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '76725023J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (31, '53608983P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (31, '89240904F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (29, '37847688S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (50, '25869114W');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (17, '39071272E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (67, '20088838V');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (38, '57073266P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (37, '54921800P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (26, '16106215M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (31, '17518926X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (11, '76411132A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (18, '24142774L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (5, '09878555D');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (44, '90321486A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (20, '67134116Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (13, '31613152C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (66, '80831406E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (67, '91284240T');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (58, '04198734S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (33, '03931812P');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (27, '99240073H');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (7, '21889814R');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (70, '53813264A');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (49, '83939464K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (58, '98541763B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (1, '74740683K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (37, '04663633S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (69, '66425557Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (34, '03049705C');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (7, '10418714J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (41, '67360665J');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (35, '43808467E');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (60, '34351579K');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (62, '28084137X');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (15, '89426223S');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (25, '62939399Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (47, '62508629B');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (31, '29841379Y');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (21, '59014633Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (16, '61465745Q');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (32, '83113173M');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (35, '97746914L');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (49, '99569728Z');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (59, '47599659D');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (53, '69328654F');
insert into TOMAS (ID_TRATAMIENTO, DNI_RESIDENTE) values (34, '99306888H');

--
--aCABA sANTI

--Mar�a

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ceviche de pescado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Paella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Huevos fritos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pizza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tallarines');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa de verduras');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Empanada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pulpo a la gallega');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Calamares');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Salmorejo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lomo saltado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lentejas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Garbanzos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Croquetas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tortilla de patatas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Risotto de calabaza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Crepes de nutella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hot dogs');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cordero Liban�s');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chuletas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tostadas mexicanas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bacalao');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa mongolesa');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hamburguesas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Arroz de mariscos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fajitas de pollo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas fritas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chilli con carne');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Costillas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chipir�n plancha');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cochinillo segoviano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lasa�a');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Milanesa de pollo a la parmesana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas bravas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pollo asado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Alb�ndigas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cus-cus marroqu�');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Nachos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ensalada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Espinacas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Mango');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fresas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pl�tano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Kiwi');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Manzana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Naranjas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Uvas');






/*
DROP TABLE RESIDENTES;
DROP TABLE ESTANCIA;
DROP TABLE MEDICAMENTO;
DROP TABLE TOMAS;
DROP TABLE TRATAMIENTO;
DROP TABLE COMIDAS_SEMANA;
DROP TABLE MENU;
DROP TABLE COMIDAS;

DROP SEQUENCE ID_MEDICAMENTO;
DROP SEQUENCE ID_TRATAMIENTO;
DROP SEQUENCE SECUENCIA_HABITACION;
DROP SEQUENCE SEQ_COMIDAS;
*/























