CREATE TABLE RESIDENTES(
    DNI_RESIDENTE               VARCHAR2(9),
    NOMBRE                      VARCHAR2(100),
    APELLIDOS                   VARCHAR2(100),
    TELEFONO_CONTACTO           VARCHAR2(13),
    FECHA_NACIMIENTO            DATE,
    ACTIVO                      NUMBER(1)DEFAULT 1,
    CONSTRAINT PK_RESIDENTES PRIMARY KEY (DNI_RESIDENTE),
    CONSTRAINT NN_RESIDENTES_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_APELLIDOS CHECK (APELLIDOS IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_TELEFONO_CONTA CHECK (TELEFONO_CONTACTO IS NOT NULL),
    CONSTRAINT NN_RESIDENTES_ACTIVO CHECK (ACTIVO IS NOT NULL)
);
CREATE TABLE ESTANCIA(
    HABITACION                  NUMBER(3),
    FECHA_ENTRADA               DATE,
    FECHA_SALIDA                DATE,
    DNI_RESIDENTE               VARCHAR2(9),               
    COSTE_MENSUAL               NUMBER(8,2),
    CONSTRAINT PK_ESTANCIA PRIMARY KEY (HABITACION),
    CONSTRAINT NN_ESTANCIA_COSTE_MENSUAL CHECK (COSTE_MENSUAL IS NOT NULL),
    CONSTRAINT CK_ESTANCIA_COSTE_MENSUAL_POS CHECK (COSTE_MENSUAL >0)
);
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO                  NUMBER(3),
    NOMBRE                          VARCHAR(100),    
    CONSTRAINT PK_ID_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL)
    );
CREATE TABLE TRATAMIENTO(
    ID_TRATAMIENTO                  NUMBER(3),
    ID_MEDICAMENTO                  NUMBER(3),
    FECHA_FIN                       DATE,
    FECHA_INICIO                    DATE,
    CANT_DESAYUNO                   NUMBER,
    CANT_COMIDA                     NUMBER,
    CANT_CENA                       NUMBER,    
    CONSTRAINT PK_ID_TRATAMIENTO PRIMARY KEY (ID_TRATAMIENTO)
);

CREATE TABLE TOMAS(
    ID_TRATAMIENTO                  NUMBER(3),
    DNI_RESIDENTE                   VARCHAR2(9),    
    CONSTRAINT PK_ID_TRATAMIENTO_DNI_RESIDENTE PRIMARY KEY (ID_TRATAMIENTO, DNI_RESIDENTE)
);


--Antonio

CREATE TABLE COMIDAS_SEMANA (
    DNI_RESIDENTE           VARCHAR2(9),
    ID_MENU_LUNES           NUMBER(3),
    ID_MENU_MARTES          NUMBER(3),
    ID_MENU_MIERCOLES       NUMBER(3),
    ID_MENU_JUEVES          NUMBER(3),
    ID_MENU_VIERNES         NUMBER(3),
    ID_MENU_SABADO          NUMBER(3),
    ID_MENU_DOMINGO         NUMBER(3),    
    CONSTRAINT PK_COMIDAS_SEMANA PRIMARY KEY (ID_MENU_LUNES, ID_MENU_MARTES, ID_MENU_MIERCOLES, ID_MENU_JUEVES, ID_MENU_VIERNES, ID_MENU_SABADO, ID_MENU_DOMINGO)
);

CREATE TABLE COMIDAS (
    ID_COMIDA               NUMBER(3),
    NOMBRE                  VARCHAR2(100),    
    CONSTRAINT PK_ID_COMIDA PRIMARY KEY (ID_COMIDA) 
);

CREATE TABLE MENU (
    ID_MENU                 NUMBER(3),
    NOMBRE                  VARCHAR2(100),
    ID_DESAYUNO             NUMBER(3),
    ID_ALMUERZO             NUMBER(3),
    ID_CENA                 NUMBER(3),   
    CONSTRAINT PK_ID_MENU PRIMARY KEY (ID_MENU)
);

--Acaba Antonio

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_COMIDAS_SEMANA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE)ON DELETE CASCADE;

ALTER TABLE ESTANCIA
ADD CONSTRAINT FK_CESTANCIA_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE) ON DELETE SET NULL;

ALTER TABLE TRATAMIENTO
ADD CONSTRAINT FK_TRATAMIENTO_MEDICAMENTO_ FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_TRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTO(ID_TRATAMIENTO)
ON DELETE SET NULL;

ALTER TABLE TOMAS
ADD CONSTRAINT FK_TOMAS_RESIDENTES FOREIGN KEY (DNI_RESIDENTE) REFERENCES RESIDENTES(DNI_RESIDENTE);

--Antonio

ALTER TABLE MENU
ADD CONSTRAINT FK_DESAYUNO FOREIGN KEY (ID_DESAYUNO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_ALMUERZO FOREIGN KEY (ID_ALMUERZO) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE MENU
ADD CONSTRAINT FK_CENA FOREIGN KEY (ID_CENA) REFERENCES COMIDAS (ID_COMIDA)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_LUNES FOREIGN KEY (ID_MENU_LUNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MARTES FOREIGN KEY (ID_MENU_MARTES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_MIERCOLES FOREIGN KEY (ID_MENU_MIERCOLES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_JUEVES FOREIGN KEY (ID_MENU_JUEVES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_VIERNES FOREIGN KEY (ID_MENU_VIERNES) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_SABADO FOREIGN KEY (ID_MENU_SABADO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

ALTER TABLE COMIDAS_SEMANA
ADD CONSTRAINT FK_DOMINGO FOREIGN KEY (ID_MENU_DOMINGO) REFERENCES MENU (ID_MENU)
ON DELETE SET NULL;

--Acaba Antonio


CREATE SEQUENCE ID_MEDICAMENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ID_TRATAMIENTO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SECUENCIA_HABITACION
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE SEQ_COMIDAS --Antonio
START WITH 1
INCREMENT BY 1;


--datos fernando
INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1000.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1200.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);

INSERT INTO ESTANCIA(HABITACION,COSTE_MENSUAL)
VALUES(SECUENCIA_HABITACION.NEXTVAL,1700.00);




insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('37254274R', 'Annamaria', 'Petriello', '5878250003', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('79138265A', 'Cass', 'Thumann', '6284667117', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('44230713B', 'Almeda', 'Diggle', '9046946601', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('14750544T', 'Burnard', 'Jardin', '6059737665', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('06321722B', 'Maurie', 'Givens', '5798764774', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('28483499T', 'Prince', 'Signorelli', '4796419249', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('28024993E', 'Robbin', 'Tuxwell', '5452301070', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('83938014C', 'Terencio', 'Dioniso', '3497439631', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('92573364C', 'Daisy', 'Lugton', '6977329210', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) 
values ('96213923R', 'Quinn', 'Batchelder', '4854912139', 1);

insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('13296008K', 'Krissy', 'Colpus', '8847621602', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('77121679G', 'Auberon', 'Wolfers', '4476786763', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('72732265O', 'Winne', 'Fashion', '3093310496', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('64117819U', 'Koral', 'Byart', '2393451038', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('83989452D', 'Jilleen', 'Matthisson', '1709083423', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('81413138G', 'Sile', 'Beeston', '6281948624', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('34783819F', 'Shari', 'Spoerl', '3267707949', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('30048206S', 'Aharon', 'Winspurr', '2814215901', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('84859859U', 'Quintana', 'Skerrett', '9373230113', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('23354752G', 'Dougie', 'Stairmand', '2029563057', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('87665457R', 'Claudius', 'Fosher', '3206734365', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('04645063S', 'Yank', 'Ivanchin', '1859426399', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('74398440K', 'Paddy', 'Wrixon', '6005941810', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('21300739J', 'Cris', 'Jope', '7193275160', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('51303266I', 'Belita', 'Lill', '4726725992', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('45487567U', 'Stephannie', 'Graveson', '2596233454', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('95643689A', 'Orelia', 'Bertwistle', '9844372338', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('64028022A', 'Chad', 'MacCard', '3816729403', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('90278068E', 'Minta', 'Aiers', '4913751417', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('13369563G', 'Georgi', 'Scammonden', '1754838589', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('54281247U', 'Vladamir', 'Witterick', '1157395421', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('57453203P', 'Bryna', 'Canizares', '4551897167', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('12271987F', 'Paula', 'Vallintine', '1473290647', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('09315857D', 'Glori', 'Maton', '9452961640', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('75635870F', 'Saraann', 'Gilbey', '3567013480', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('77325173L', 'Alyse', 'Hars', '7516211914', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('27951187R', 'Jemmy', 'Ranns', '8557064031', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('75478069H', 'Idette', 'Brothwell', '6652098508', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('26925808N', 'Mara', 'Mc Trusty', '2472352691', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('42491395N', 'Ashton', 'Leach', '1362086112', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('03323118R', 'Griselda', 'Marshman', '5453471825', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('87590576Y', 'Brose', 'McKevitt', '9618260398', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('13078824H', 'Erda', 'Cella', '8936487476', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('71484497N', 'Christyna', 'Gaudon', '9113459755', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('47500923B', 'Gaynor', 'Marunchak', '9182041984', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('11459474J', 'Sherm', 'Dawbery', '3405702863', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('75703761T', 'Anthiathia', 'Maccaddie', '4827099434', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('59015463Y', 'Pauly', 'Jaine', '9612735941', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('77192689X', 'Eda', 'Bassett', '8509088636', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('48485438R', 'Bentlee', 'Landis', '8047448466', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('81953217K', 'Layton', 'Devas', '1379058207', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('61988075A', 'Jacki', 'Bollis', '8169336680', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('19785515I', 'Lenee', 'McAnellye', '1546899407', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('13226098F', 'Matilda', 'Valintine', '5499592809', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('00072151X', 'Sephira', 'Franscioni', '1624880433', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('94263292Q', 'Griff', 'Sheards', '9751756690', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('02941544U', 'Dori', 'Sheilds', '6982561103', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('38307766Q', 'Celina', 'Reubbens', '8821345845', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('74874724T', 'Kiah', 'Miere', '9229971413', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('84715361J', 'Quincy', 'Streat', '5204259598', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('28210785J', 'Gussi', 'Wyldish', '1646116315', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('12435796G', 'Lorant', 'Gores', '5618457928', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('52125404Y', 'Dare', 'Conahy', '2435476898', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('59804788B', 'Traver', 'Jewks', '8091136900', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('64378680S', 'Obadiah', 'Gierardi', '5357679296', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('24907400L', 'Zora', 'Geertje', '6973343144', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('53757092I', 'Constantia', 'Salmond', '1127178159', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('99925207U', 'Laurie', 'Judd', '3525638870', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('46681443Z', 'Parke', 'Froude', '5522644052', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('99730697P', 'Roxana', 'Tarver', '8446033415', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('62692285P', 'Renard', 'Robrose', '8507475580', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('16160113L', 'Shel', 'Eplate', '9341067099', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('17769058E', 'Adan', 'Gatley', '8773166247', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('34299559W', 'Arleta', 'Kleinsmuntz', '1655897496', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('18544065Q', 'Rubi', 'Somes', '1809813564', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('54058215V', 'Annabelle', 'Bestiman', '4625956781', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('21894568F', 'Chick', 'Kauschke', '6962450378', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('02921278C', 'Eugenius', 'Charlon', '1097831682', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('71291732O', 'Prisca', 'Maidlow', '3063500548', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('39281890R', 'Page', 'Eble', '2508142360', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('60325803E', 'Kiley', 'Longstaffe', '8501335434', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('62170688K', 'Shane', 'Madner', '9044346760', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('42597746D', 'Ayn', 'Gouly', '8333841388', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('10656644N', 'Gerhardine', 'Ripper', '8419878500', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('03976896T', 'Maxie', 'Ofener', '2639165777', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('72023082G', 'Luci', 'Tibalt', '6648825371', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('07663101J', 'Tilda', 'Plant', '9397890448', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('21818542H', 'Manny', 'Lucock', '5304038983', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('93638918R', 'Elysee', 'Wilkison', '8373915336', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('99833236T', 'Mellisent', 'McGilbon', '2618498681', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('52928387D', 'Barty', 'Youle', '5958099070', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('21681578L', 'Nolan', 'Earsman', '6408620018', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('58274416G', 'Sandor', 'Gales', '3678949600', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('33709779Z', 'Fayre', 'Rose', '5638844060', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('35145985C', 'Laurence', 'Scurrell', '6151049620', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('34072985N', 'Margeaux', 'Taffee', '3314454459', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('24975136Y', 'Ki', 'Labdon', '9327938284', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('89376059D', 'Erinna', 'Sket', '6447330773', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('79318121R', 'Tanny', 'Leving', '1646177182', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('21318687C', 'Gretel', 'Addicote', '7599152696', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('67656132Q', 'Milty', 'Whinray', '7725620218', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('92687099O', 'Rance', 'Banfill', '3772382576', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('12611162G', 'Annmaria', 'Pughsley', '2553618227', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('83298816W', 'Elinore', 'Rutherforth', '3348362546', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('78769126C', 'Kasey', 'Pates', '8195516332', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('45307559M', 'Izzy', 'Masden', '2427457626', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('42447501Q', 'Carley', 'Lakey', '3757819092', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('33191300F', 'Marijo', 'Bythway', '5511251757', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('83237744A', 'Gage', 'Frenzl', '5134724993', 1);
insert into RESIDENTES (DNI_RESIDENTE, NOMBRE, APELLIDOS, TELEFONO_CONTACTO, ACTIVO) values ('22043009G', 'Stefania', 'Curr', '9978652540', 1);


UPDATE ESTANCIA
SET DNI_RESIDENTE = '37254274R'
WHERE HABITACION=1;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '96213923R'
WHERE HABITACION=2;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '92573364C'
WHERE HABITACION=3;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '83938014C'
WHERE HABITACION=4;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '28024993E'
WHERE HABITACION=5;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '28483499T'
WHERE HABITACION=6;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '06321722B'
WHERE HABITACION=7;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '14750544T'
WHERE HABITACION=8;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '44230713B'
WHERE HABITACION=9;

UPDATE ESTANCIA
SET DNI_RESIDENTE = '79138265A'
WHERE HABITACION=10;


--DATOS santi
INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'SIMVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL, 'ASPIRINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'OMEOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LEXOTIROXINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'RAMIPRIL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PARACETAMOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'VENTOLIN');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FLIXOTIDE');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'FORTASEC');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'SILDENAFILO');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ALMAX');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'ATORVASTATINA');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'LANSOPRAZOL');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PULMICOR');

INSERT INTO MEDICAMENTO(ID_MEDICAMENTO,NOMBRE)
VALUES (ID_MEDICAMENTO.NEXTVAL,'PRIMPERAN');

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 15, '23/09/2020', '04/10/2020', 1, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 6, '19/02/2020', '24/09/2020', 1, 1.5, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 9, '27/07/2020', '04/04/2020', 1, 1.5, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 13, '30/05/2020', '20/04/2020', 2, 1.5, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 4, '24/07/2020', '22/02/2020', 1, 1.5, 2);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 2, '08/11/2020', '06/10/2020', 1, 2.0, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 1, '11/04/2020', '30/06/2020', 2, 1, 2);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 8, '22/10/2020', '12/09/2020', 1, 2, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 14, '16/04/2020', '15/05/2020', 2, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 13, '04/11/2020', '30/11/2020', 1.0, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 9, '08/12/2020', '21/10/2020', 1, 1.5, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 1, '11/11/2020', '18/09/2020', 2.0, 1, 2.0);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 15, '19/10/2020', '27/09/2020', 2, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) 
values (ID_TRATAMIENTO.NEXTVAL, 12, '25/11/2020', '23/05/2020', 1.0, 1, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 4, '11/07/2020', '06/11/2020', 1.5, 1.5, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 4, '31/03/2020', '17/10/2020', 2, 1.5, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 7, '11/04/2020', '13/03/2020', 2, 2, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 3, '23/04/2020', '18/09/2020', 1, 1.5, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 11, '01/05/2020', '04/06/2020', 1, 1.5, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 11, '08/11/2020', '03/07/2020', 2.0, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 8, '04/04/2020', '08/02/2020', 1, 2, 1.5);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 6, '30/12/2020', '16/11/2020', 1, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 13, '13/08/2020', '23/11/2020', 2, 1.5, 2);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 6, '07/04/2020', '24/07/2020', 1.5, 1, 2);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 6, '31/08/2020', '14/12/2020', 1, 2, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 2, '25/03/2020', '03/03/2020', 1, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 15, '23/07/2020', '03/05/2020', 1, 1, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA) 
values (ID_TRATAMIENTO.NEXTVAL, 8, '07/08/2020', '06/05/2020', 1, 1.5, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 9, '05/08/2020', '13/06/2020', 1, 2, 1);

insert into TRATAMIENTO (ID_TRATAMIENTO, ID_MEDICAMENTO, FECHA_INICIO, FECHA_FIN, CANT_DESAYUNO, CANT_COMIDA, CANT_CENA)
values (ID_TRATAMIENTO.NEXTVAL, 15, '07/08/2020', '10/03/2020', 1.5, 1, 1.5);

--Tomas
/*
DNI:
96213923R
44230713B
37254274R
79138265A
14750544T
06321722B
28483499T
28024993E
83938014C
92573364C

*/
--aCABA sANTI

--Mar�a

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Macarrones');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ceviche de pescado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Paella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Huevos fritos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pizza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tallarines');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa de verduras');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Empanada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pulpo a la gallega');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Calamares');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Salmorejo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lomo saltado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lentejas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Garbanzos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Croquetas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tortilla de patatas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Risotto de calabaza');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Crepes de nutella');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hot dogs');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cordero Liban�s');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chuletas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Tostadas mexicanas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Bacalao');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Sopa mongolesa');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Hamburguesas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Arroz de mariscos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fajitas de pollo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas fritas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chilli con carne');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Costillas de cerdo');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Chipir�n plancha');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cochinillo segoviano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Lasa�a');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Milanesa de pollo a la parmesana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Patatas bravas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pollo asado');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Alb�ndigas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Cus-cus marroqu�');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Nachos');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Ensalada');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Espinacas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Mango');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Fresas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Pl�tano');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Kiwi');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Manzana');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Naranjas');

INSERT INTO COMIDAS
VALUES (SEQ_COMIDAS.NEXTVAL, 'Uvas');






/*
DROP TABLE RESIDENTES;
DROP TABLE ESTANCIA;
DROP TABLE MEDICAMENTO;
DROP TABLE TOMAS;
DROP TABLE TRATAMIENTO;
DROP TABLE COMIDAS_SEMANA;
DROP TABLE MENU;
DROP TABLE COMIDAS;

DROP SEQUENCE ID_MEDICAMENTO;
DROP SEQUENCE ID_TRATAMIENTO;
DROP SEQUENCE SECUENCIA_HABITACION;
DROP SEQUENCE SEQ_COMIDAS;
*/























